package by.tc.task01.entity;

public enum Option {
	
	POWER_CONSUMPTION, WEIGHT, CAPACITY, DEPTH, HEIGHT, WIDTH, BATTERY_CAPACITY, OS, MEMORY_ROM, SYSTEM_MEMORY, CPU,
	DISPLAY_INCHES, FREEZER_CAPACITY, OVERALL_CAPACITY, FILTER_TYPE, BAG_TYPE, WAND_TYPE, MOTOR_SPEED_REGULATION,
	CLEANING_WIDTH, FLASH_MEMORY_CAPACITY, COLOR, NUMBER_OF_SPEAKERS, FREQUENCY_RANGE, CORD_LENGTH, DISPLAY_INCHS

}
